# permissions to do viewer lagoontasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagoontask-viewer-role
rules:
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoontasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoontasks/status
  verbs:
  - get
