# permissions to do edit lagoontasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagoontask-editor-role
rules:
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoontasks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoontasks/status
  verbs:
  - get
  - patch
  - update
