# permissions to do viewer lagoonbuilds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagoonbuild-viewer-role
rules:
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoonbuilds
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lagoon.amazee.io
  resources:
  - lagoonbuilds/status
  verbs:
  - get
