apiVersion: v1
entries:
  lagoon-builddeploy:
  - apiVersion: v2
    appVersion: 0.1.3
    created: "2020-09-24T16:47:40.514024+10:00"
    description: A Helm chart for lagoon-builddeploy
    digest: 7c97f2815d38e0a2f6d1041670eec750dcb88484105b9b231746a6649915ab0f
    name: lagoon-builddeploy
    type: application
    urls:
    - lagoon-builddeploy-0.1.3.tgz
    version: 0.1.3
  - apiVersion: v2
    appVersion: 0.1.2
    created: "2020-09-24T16:47:40.513451+10:00"
    description: A Helm chart for lagoon-builddeploy
    digest: 7616e507ebdac9a8fa081b1925428dff700cee46e3d0948ee5f343864bf73873
    name: lagoon-builddeploy
    type: application
    urls:
    - lagoon-builddeploy-0.1.2.tgz
    version: 0.1.2
  - apiVersion: v2
    appVersion: 0.1.1
    created: "2020-09-24T16:47:40.510981+10:00"
    description: A Helm chart for lagoon-builddeploy
    digest: 1fa0435d49d0dd2762029cf140d5c6e233f00253bcdf60ca9a113d7dac3a73fd
    name: lagoon-builddeploy
    type: application
    urls:
    - lagoon-builddeploy-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: 0.1.0
    created: "2020-09-24T16:47:40.509553+10:00"
    description: A Helm chart for lagoon-builddeploy
    digest: de42c5e64e32c18a5ad15e138afe1eadec4e742eeb42f77faaf3188a8d25d1e3
    name: lagoon-builddeploy
    type: application
    urls:
    - lagoon-builddeploy-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-24T16:47:40.508261+10:00"
