apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lagoon-builddeploy.fullname" . }}
  labels:
    {{- include "lagoon-builddeploy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lagoon-builddeploy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "lagoon-builddeploy.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "lagoon-builddeploy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=10
          image: "{{ .Values.kubeRbacProxy.image.repository }}:{{ .Values.kubeRbacProxy.image.tag }}"
          name: kube-rbac-proxy
          ports:
          - containerPort: 8443
            name: https
        - args:          
      {{- range $key, $value := .Values.extraArgs }}
          {{- if $value }}
          - --{{ $key }}={{ $value }}
          {{- else }}
          - --{{ $key }}
          {{- end }}
      {{- end }}
          {{- if .Values.vars.isOpenshift }}
          - --is-openshift
          {{- end }}
          {{- if .Values.vars.randomPrefix }}
          - --random-prefix
          {{- end }}
          command:
          - /manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            - name: RABBITMQ_USERNAME
              value: '{{ .Values.vars.rabbitUsername }}'
            - name: RABBITMQ_PASSWORD
              value: '{{ .Values.vars.rabbitPassword }}'
            - name: RABBITMQ_HOSTNAME
              value: '{{ .Values.vars.rabbitHostname }}'
            - name: LAGOON_TARGET_NAME
              value: '{{ .Values.vars.lagoonTargetName }}'
            - name: PENDING_MESSAGE_CRON
              value: '{{ .Values.vars.pendingMessageCron }}'
            - name: OVERRIDE_BUILD_DEPLOY_DIND_IMAGE
              value: '{{ .Values.vars.overrideBuildDeployImage }}'
            - name: NAMESPACE_PREFIX
              value: '{{ .Values.vars.namespacePrefix }}'
            - name: CONTROLLER_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          name: manager
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
