apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lagoon-builddeploy.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "lagoon-builddeploy.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "lagoon-builddeploy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}